### PR TITLE
chore: run go test in check action

### PR DESCRIPTION
**Pull request by hhyasdf**
# Pull Request Description

## Describe what this PR does / why we need it
Run go test in check action.

## Does this pull request fix one issue?

NONE

## Describe how you did it
Change github actions workflow.

## Describe how to verify it
This pr will trigger a github actions process.

## Special notes for reviews

### CODE REVIEW

**Review by mars1024 — COMMENTED** [review]
I don't think a cron job is suitable for coverage check, what we really need is checking and displaying coverage change each time push.

**Comment by hhyasdf** [comment]
> I don't think a cron job is suitable for coverage check, what we really need is checking and displaying coverage change each time push.

Done~

**Comment by hhyasdf** [comment]
There is a bug for a pr which is from a forked repository for codecov-action, cause of the github secrets of source repo cannot be shared by forked repo. So I change the secret to a clear string ~

**Review by mars1024 — APPROVED** [review]
/lgtm, well done!

**Pull request merged**
